module.exports = [
  "Avengers: Endgame",
  "Captain Marvel",
  "Avengers: Infinity War",
  "Hellboy",
  "After",
  "Cold Pursuit",
  "The Avengers",
  "Doraemon the Movie: Nobita's Treasure Island",
  "Shazam!",
  "Avengers: Age of Ultron",
  "Glass",
  "What Men Want",
  "How to Train Your Dragon: The Hidden World",
  "Guardians of the Galaxy",
  "Black Panther",
  "Kamen Rider Heisei Generations FOREVER",
  "Fall in Love at First Kiss",
  "Instant Family",
  "Guardians of the Galaxy Vol. 2",
  "Thor: Ragnarok",
  "Cars",
  "Redcon-1",
  "Iron Man",
  "The Prodigy",
  "Bumblebee",
  "Ant-Man and the Wasp",
  "Thor",
  "Dumbo",
  "Captain America: Civil War",
  "POKÉMON Detective Pikachu",
  "Spider-Man: Into the Spider-Verse",
  "Nanny McPhee and the Big Bang",
  "Us",
  "High Life",
  "Dragged Across Concrete",
  "Aquaman",
  "Captain America: The First Avenger",
  "Alita: Battle Angel",
  "Escape Room",
  "The Lego Movie 2: The Second Part",
  "Ralph Breaks the Internet",
  "Robin Hood",
  "Transformers: Beginnings",
  "Logan",
  "Doctor Strange",
  "Vaarikkuzhiyile Kolapathakam",
  "Happy Death Day 2U",
  "Fate/stay night: Heaven’s Feel II. lost butterfly",
  "Thor: The Dark World",
  "Detective Conan: The Fist of Blue Sapphire",
  "The Wandering Earth",
  "Pet Sematary",
  "Venom",
  "Iron Man 2",
  "The Mule",
  "Mile 22",
  "Breakthrough",
  "Arctic",
  "Edge of Tomorrow",
  "Deadpool 2",
  "BlacKkKlansman",
  "Replicas",
  "The Lord of the Rings: The Fellowship of the Ring",
  "Mortal Engines",
  "Iron Man 3",
  "Fighting with My Family",
  "Harry Potter and the Philosopher's Stone",
  "The Silence",
  "Mary Poppins Returns",
  "Bohemian Rhapsody",
  "Twilight",
  "Someone Great",
  "John Wick",
  "Goosebumps",
  "The First Purge",
  "13 Sins",
  "Maggie",
  "Star Wars: The Last Jedi",
  "The Perfect Date",
  "Wonder Woman",
  "Extremely Wicked, Shockingly Evil and Vile",
  "Destroyer",
  "It's a Wonderful Life",
  "The Sisters Brothers",
  "Trainspotting",
  "Inception",
  "Death Wish",
  "The Incredible Hulk",
  "UglyDolls",
  "Polar",
  "Harry Potter and the Chamber of Secrets",
  "Star Wars",
  "Jigsaw",
  "Anthony Jeselnik: Fire in the Maternity Ward",
  "Kanchana 3",
  "Loving Vincent",
  "Friends with Kids",
  "The Lord of the Rings: The Return of the King",
  "The Highwaymen",
  "Mission: Impossible - Fallout",
  "Pirates of the Caribbean: The Curse of the Black Pearl",
  "A Wrinkle in Time",
  "Miss Bala",
  "Deadpool",
  "The Imitation Game",
  "The Kid Who Would Be King",
  "Se7en",
  "The Curious Case of Benjamin Button",
  "A Bad Moms Christmas",
  "Solo: A Star Wars Story",
  "Die Hard",
  "Missing Link",
  "Passenger 57",
  "The Matrix",
  "Texas Chainsaw 3D",
  "Eighth Grade",
  "Shaun the Sheep Movie",
  "Mandy",
  "The Dark Knight",
  "Justice League",
  "Fury",
  "Terminator Genisys",
  "The Emoji Movie",
  "Inside Out",
  "Taken 3",
  "Anon",
  "Suburbicon",
  "Jurassic World: Fallen Kingdom",
  "Footloose",
  "The Intruder",
  "The Man Who Knew Too Much",
  "Wrong Turn 2: Dead End",
  "Jessica Forever",
  "The Client",
  "The Martian",
  "Planes",
  "Blade Runner 2049",
  "The Transporter Refueled",
  "Outlaw King",
  "Truth or Dare",
  "Little Women",
  "Disclosure",
  "Home Alone 4",
  "Vice",
  "Triple Threat",
  "The Smurfs 2",
  "X-Men: Days of Future Past",
  "Friday the 13th Part 2",
  "Pitch Perfect 3",
  "Free State of Jones",
  "X-Men: Apocalypse",
  "Re: Zero kara Hajimeru Isekai Seikatsu - Memory Snow",
  "Ironclad",
  "Personal Shopper",
  "Teenage Mutant Ninja Turtles",
  "Pulp Fiction",
  "The Shawshank Redemption",
  "The Last Legion",
  "47 Meters Down",
  "Harry Potter and the Deathly Hallows: Part 2",
  "The Lord of the Rings: The Two Towers",
  "Battle of the Sexes",
  "To All the Boys I've Loved Before",
  "Don't Say a Word",
  "The Gunman",
  "Scooby-Doo 2: Monsters Unleashed",
  "Mad Max: Fury Road",
  "On the Basis of Sex",
  "The Head Hunter",
  "LelleBelle",
  "The Meg",
  "Batman v Superman: Dawn of Justice",
  "The Lion King 1½",
  "Odd Thomas",
  "Alexander and the Terrible, Horrible, No Good, Very Bad Day",
  "Pacific Rim: Uprising",
  "Rough Night",
  "Frankenstein",
  "Arthur and the Invisibles",
  "The Belko Experiment",
  "The Tale of Despereaux",
  "Game of Thrones: The Last Watch",
  "Silent Hill: Revelation 3D",
  "Tale of Tales",
  "Jurassic World",
  "The Wind That Shakes the Barley",
  "Love Happens",
  "Gone Girl",
  "The Railway Man",
  "Herbie Fully Loaded",
  "Anthropoid",
  "15 Minutes",
  "Red Cliff",
  "Invasion of the Body Snatchers",
  "Police Academy 4: Citizens on Patrol",
  "Harry Potter and the Order of the Phoenix",
  "Get Out",
  "The Water Horse",
  "Force Majeure",
  "Toni Erdmann"
]
